#apiVersion: v1
#kind: Pod
#metadata:
#  name: sample1
#spec:
#  containers:
#    - name: nginx
#      image: nginx
#multi containers
apiVersion: v1
kind: Pod
metadata:
  name: sample2
spec:
  containers:
    - name: nginx
      image: nginx
    - name: centos
      image: centos:7
      command:
        - "sleep"
        - "10000"