- name: copy mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install mysql server and ansible mysql server
  yum:
    name: 
    - mysql-community-server
    - MySQL-python
    state: installed

- name: start mysql services
  systemd:
    name: mysqld
    state: start
    enabled: true

