- hosts: localhost
  become: yes
  tasks: 

    - name: instalting utils
      yum:
        name: yum-utils
        state: present
    - name: repository for terraform
      yum_repository:
        name: hashicorp
        description: hashicorp.repo file
        baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        state: present

    - name: terraform installation
      yum:
        name: terraform 
        state: installed
