- hosts: localhost
  become: yes
  tasks: 
    - name: repository for terraform
      yum_repository:
        name: hashicrop.repo
        description: hashicrop.repo file
        baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        state: present

    - name: instalting utils
      yum:
        name: yum-utils
        state: present

    - name: terraform installation
      yum:
        name: terraform 
        state: installed
