- name: Deploy terraform
  hosts: localhost
  gather_facts: false
  become: yes
  tasks: 
    - name: yum packages installation
      yum: 
        name: {{item}}
        state: latest
        with_items:
            - wget
    - name: terraform install
      unarchive: 
        src: https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_linux_amd64.zip
        dest: /usr/bin
        remote_src: true
  